services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "~/app/problems:/app/problems:ro"
      - "~/app/submissions:/app/submissions:rw"
      - "~/app/log:/app/log:rw"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:17
    ports:
      - 5432:5432
    env_file:
      - .env