"""Add directory to submission

Revision ID: afdd846dc8ec
Revises: 8b64d1c837e4
Create Date: 2023-03-01 02:47:00.246093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afdd846dc8ec'
down_revision = '8b64d1c837e4'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('directory', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'directory')
    # ### end Alembic commands ###
