"""add end time

Revision ID: 21d2fa22a5d2
Revises: c0db785d488e
Create Date: 2023-03-02 18:21:04.114140

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "21d2fa22a5d2"
down_revision = "c0db785d488e"
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("progcomps", sa.Column("end_time", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("progcomps", "end_time")
    # ### end Alembic commands ###
