"""Made submission.problem_id non-nullable

Revision ID: 2f13e11e904a
Revises: f9add14a52b5
Create Date: 2025-01-01 18:46:50.094354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f13e11e904a'
down_revision = 'f9add14a52b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('problem_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('problem_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
