"""empty message

Revision ID: 433eb9f25ad4
Revises: ef13138f7688
Create Date: 2025-01-16 21:22:48.530461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433eb9f25ad4'
down_revision = 'ef13138f7688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('passwd', sa.String(), nullable=True),
    sa.Column('pc_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_sessions')
    # ### end Alembic commands ###
