"""Add Team Member Table

Revision ID: 51621a2826da
Revises: 2f13e11e904a
Create Date: 2025-01-10 10:14:43.905455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51621a2826da'
down_revision = '2f13e11e904a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'team_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_members')
    # ### end Alembic commands ###
