"""Added pc.max_team_members

Revision ID: 7c60f16e2cb8
Revises: ff57a6f17048
Create Date: 2025-01-10 16:17:06.732612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c60f16e2cb8'
down_revision = 'ff57a6f17048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progcomps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_team_members', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progcomps', schema=None) as batch_op:
        batch_op.drop_column('max_team_members')

    # ### end Alembic commands ###
