"""Add max score

Revision ID: 9cb05fd6f6a5
Revises: afdd846dc8ec
Create Date: 2023-03-01 03:45:05.623412

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9cb05fd6f6a5"
down_revision = "afdd846dc8ec"
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tests", sa.Column("max_score", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tests", "max_score")
    # ### end Alembic commands ###
