"""Add problem enabled flag

Revision ID: c4e15b008d3d
Revises: 9cb05fd6f6a5
Create Date: 2023-03-01 12:35:16.603955

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c4e15b008d3d"
down_revision = "9cb05fd6f6a5"
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "problems",
        sa.Column(
            "enabled",
            sa.Boolean(),
            nullable=False,
            server_default="t",
            default=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("problems", "enabled")
    # ### end Alembic commands ###
