"""Add blacklist boolean flag to teams table

Revision ID: e090f2766628
Revises: dcc5c2df85e7
Create Date: 2024-12-31 10:28:14.928951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e090f2766628'
down_revision = 'dcc5c2df85e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blacklist', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('blacklist')

    # ### end Alembic commands ###
