"""add leaderboard toggle

Revision ID: e3eed1c081ca
Revises: c4e15b008d3d
Create Date: 2023-03-01 14:12:27.360617

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e3eed1c081ca"
down_revision = "c4e15b008d3d"
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "progcomps",
        sa.Column(
            "show_leaderboard",
            sa.Boolean(),
            nullable=False,
            server_default="f",
            default=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("progcomps", "show_leaderboard")
    # ### end Alembic commands ###
