"""Created Admin Sessions Table

Revision ID: ef13138f7688
Revises: 7c60f16e2cb8
Create Date: 2025-01-15 15:02:52.135039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef13138f7688'
down_revision = '7c60f16e2cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('addr', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_sessions')
    # ### end Alembic commands ###
