"""Change blacklist flag to boolean in model

Revision ID: f9add14a52b5
Revises: e090f2766628
Create Date: 2024-12-31 17:03:18.520371

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f9add14a52b5"
down_revision = "e090f2766628"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.alter_column(
            "blacklist",
            existing_type=sa.INTEGER(),
            type_=sa.Boolean(),
            existing_nullable=True,
            postgresql_using="CASE WHEN blacklist = 1 THEN true ELSE false END"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.alter_column(
            "blacklist",
            existing_type=sa.Boolean(),
            type_=sa.INTEGER(),
            existing_nullable=True,
            postgresql_using="CASE WHEN blacklist THEN 1 ELSE 0 END"
        )

    # ### end Alembic commands ###
